# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-28 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pasta_pastas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasta',
            name='pastas',
        ),
        migrations.AddField(
            model_name='pasta',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pasta'),
        ),
    ]
