# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-02 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_pasta_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pasta',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
