# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_usuario_compartilhados_cmg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compartilhado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Arquivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Usuario')),
            ],
        ),
    ]
