# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_compartilhado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='compartilhados_cmg',
        ),
    ]
