# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 23:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_usuario_compartilhados_cmg'),
    ]

    operations = [
        migrations.AddField(
            model_name='compartilhado',
            name='habilitado',
            field=models.BooleanField(default=datetime.datetime(2016, 9, 8, 23, 18, 11, 904000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
