# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-08 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_compartilhado_habilitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compartilhado',
            name='habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
